### ISSUE TITLE
"Options" button only works once

### ISSUE THREAD

**Issue by JonathanHarford** [rmrt1n/contact.app-clj#1]
When the site loads, clicking "options" on one of the contacts shows a menu with two links and a button. If I do one of the following:
* Delete a contact
* Edit a contact
* View a contact (and then click "back")
Then the options buttons no longer have an effect. No error shows in the console. This happens for me in both Firefox and Chrome (Mac).

Great htmx example, though. :)

**Comment by rmrt1n** [comment]
Hey @JonathanHarford, thanks for reporting this bug! It's fixed in the latest commit.
